### ISSUE TITLE
mate-tweak wrongly detects only 2 panel layouts - GNOME2 and OpenSuSE instead of many others

### ISSUE THREAD

**Issue by N0rbert** [ubuntu-mate/mate-tweak#78]
Steps to reproduce:
1a. Boot Ubuntu MATE 20.10 live session
1b. Have Ubuntu MATE 20.10 installed
2. Launch MATE Tweak
3. Switch to Panel tab
4. Click on *Select panel layout to change the user interface* dropdown menu

Expected results:
* many panel layouts are presented, use can switch to any of it

Actual results:
* only 2 panel layouts are shown - GNOME2 and OpenSuSE instead

ProblemType: Bug
DistroRelease: Ubuntu 20.10
Package: mate-tweak 20.04.0-2

Downstream bug - https://pad.lv/1894386 .

**Comment by saivinoba** [comment]
The condition for `self.indicators_available = True` is not satisfied in `mate-tweak`. The only items listed, 'GNOME2' and 'OpenSUSE' have test `not self.indicators_available` set which is satisfied.

Installing `indicator-datetime` (if you had removed it) and `indicator-session` will get back the full panel list.

Since we are moving to ayatana-indicators the datetime and session conditions need to be updated.

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/ubuntu-mate/mate-tweak/releases/tag/20.10.0
